// Chart color palette
export const chartColors = {
  primary: '#3B82F6',
  success: '#10B981',
  danger: '#EF4444',
  warning: '#F59E0B',
  info: '#6366F1',
  purple: '#8B5CF6',
  pink: '#EC4899',
  teal: '#14B8A6',
  orange: '#F97316',
  categories: ['#3B82F6', '#10B981', '#F59E0B', '#EF4444', '#8B5CF6', '#EC4899', '#14B8A6', '#F97316']
};

// Date range presets
export const datePresets = [
  { key: 'today', days: 0 },
  { key: 'last7Days', days: 7 },
  { key: 'last30Days', days: 30 },
  { key: 'last90Days', days: 90 },
];

// Translations
export const translations = {
  en: {
    title: 'Stock Analytics',
    overview: 'Overview',
    movements: 'Movements',
    health: 'Inventory Health',
    warehouses: 'Warehouses',
    filters: 'Filters',
    dateRange: 'Date Range',
    warehouse: 'Warehouse',
    category: 'Category',
    product: 'Product',
    apply: 'Apply',
    reset: 'Reset',
    export: 'Export',
    exportCSV: 'Export CSV',
    today: 'Today',
    last7Days: 'Last 7 Days',
    last30Days: 'Last 30 Days',
    last90Days: 'Last 90 Days',
    custom: 'Custom',
    allWarehouses: 'All Warehouses',
    allCategories: 'All Categories',
    totalStockValue: 'Total Stock Value',
    totalProducts: 'Total Products',
    totalLots: 'Total Lots',
    avgTurnover: 'Avg Turnover Rate',
    stockValueTrend: 'Stock Value Trend',
    categoryDistribution: 'Category Distribution',
    topProductsByValue: 'Top Products by Value',
    movementTrend: 'Movement Trend',
    movementTypeDistribution: 'Movement Type Distribution',
    topProductsByMovement: 'Top Products by Movement',
    movementSummary: 'Movement Summary',
    stockLevelDistribution: 'Stock Level Distribution',
    expiryAnalysis: 'Expiry Analysis',
    agingAnalysis: 'Stock Aging',
    reorderRecommendations: 'Reorder Recommendations',
    warehouseStats: 'Warehouse Statistics',
    warehouseComparison: 'Warehouse Comparison',
    warehouseUtilization: 'Warehouse Utilization',
    loading: 'Loading...',
    noData: 'No data available',
    in: 'IN',
    out: 'OUT',
    adjustment: 'Adjustment',
    transfer: 'Transfer',
    return: 'Return',
    lowStock: 'Low Stock',
    normal: 'Normal',
    overstock: 'Overstock',
    outOfStock: 'Out of Stock',
    expired: 'Expired',
    expiringSoon: 'Expiring Soon',
    productName: 'Product',
    sku: 'SKU',
    current: 'Current',
    reorderPoint: 'Reorder Point',
    toOrder: 'To Order',
    warehouseName: 'Warehouse',
    quantity: 'Quantity',
    value: 'Value',
    inMovements: 'IN',
    outMovements: 'OUT',
    netChange: 'Net Change',
    utilization: 'Utilization',
    period: 'Period',
    net: 'Net',
    from: 'From',
    to: 'To',
    products: 'Products',
    count: 'Count',
    percentage: 'Percentage',
    range: 'Range',
    expiryDate: 'Expiry Date',
    daysUntilExpiry: 'Days Until Expiry',
    viewAll: 'View All',
    totalQuantity: 'Total Quantity',
    productCount: 'Product Count',
  },
  fr: {
    title: 'Analytique de Stock',
    overview: 'Aperçu',
    movements: 'Mouvements',
    health: 'Santé du Stock',
    warehouses: 'Entrepôts',
    filters: 'Filtres',
    dateRange: 'Période',
    warehouse: 'Entrepôt',
    category: 'Catégorie',
    product: 'Produit',
    apply: 'Appliquer',
    reset: 'Réinitialiser',
    export: 'Exporter',
    exportCSV: 'Exporter CSV',
    today: 'Aujourd\'hui',
    last7Days: '7 derniers jours',
    last30Days: '30 derniers jours',
    last90Days: '90 derniers jours',
    custom: 'Personnalisé',
    allWarehouses: 'Tous les entrepôts',
    allCategories: 'Toutes les catégories',
    totalStockValue: 'Valeur Totale du Stock',
    totalProducts: 'Total Produits',
    totalLots: 'Total Lots',
    avgTurnover: 'Taux de Rotation Moyen',
    stockValueTrend: 'Tendance de la Valeur du Stock',
    categoryDistribution: 'Distribution par Catégorie',
    topProductsByValue: 'Top Produits par Valeur',
    movementTrend: 'Tendance des Mouvements',
    movementTypeDistribution: 'Distribution par Type de Mouvement',
    topProductsByMovement: 'Top Produits par Mouvement',
    movementSummary: 'Résumé des Mouvements',
    stockLevelDistribution: 'Distribution des Niveaux de Stock',
    expiryAnalysis: 'Analyse des Expirations',
    agingAnalysis: 'Vieillissement du Stock',
    reorderRecommendations: 'Recommandations de Réapprovisionnement',
    warehouseStats: 'Statistiques des Entrepôts',
    warehouseComparison: 'Comparaison des Entrepôts',
    warehouseUtilization: 'Utilisation des Entrepôts',
    loading: 'Chargement...',
    noData: 'Aucune donnée disponible',
    in: 'ENTRÉE',
    out: 'SORTIE',
    adjustment: 'Ajustement',
    transfer: 'Transfert',
    return: 'Retour',
    lowStock: 'Stock Faible',
    normal: 'Normal',
    overstock: 'Surstock',
    outOfStock: 'Rupture de Stock',
    expired: 'Expiré',
    expiringSoon: 'Expire Bientôt',
    productName: 'Produit',
    sku: 'SKU',
    current: 'Actuel',
    reorderPoint: 'Point de Réapprovisionnement',
    toOrder: 'À Commander',
    warehouseName: 'Entrepôt',
    quantity: 'Quantité',
    value: 'Valeur',
    inMovements: 'ENTRÉE',
    outMovements: 'SORTIE',
    netChange: 'Variation Nette',
    utilization: 'Utilisation',
    period: 'Période',
    net: 'Net',
    from: 'De',
    to: 'À',
    products: 'Produits',
    count: 'Nombre',
    percentage: 'Pourcentage',
    range: 'Plage',
    expiryDate: 'Date d\'Expiration',
    daysUntilExpiry: 'Jours Avant Expiration',
    viewAll: 'Voir Tout',
    totalQuantity: 'Quantité Totale',
    productCount: 'Nombre de Produits',
  },
};

export type TranslationKey = keyof typeof translations.en;