# Please edit this file to reflect the correct migration history.
# Read more about migration files: https://pris.ly/d/migration-files

migration_name = "add_default_commission_settings"
datamodel = """
// This is your Prisma schema file,
// learn more about it in the docs: https://pris.ly/d/prisma-schema

generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model DefaultCommissionSettings {
  id                    String   @id @default(cuid())
  name                  String   @unique // "default" for the main settings
  settings              Json     // All commission settings in flexible JSON structure
  isActive              Boolean  @default(true)
  createdAt             DateTime @default(now())
  updatedAt             DateTime @updatedAt
  
  @@map("default_commission_settings")
}
"""